"""
Deterministic Test Replay (Section 12).

A TestRun's Trace rows already store everything a replay needs (see
app/models/trace.py):

    - scenario_id           -> which Scenario was tested
    - test_run.version      -> which Agent version was tested
    - trace.events          -> the exact ordered record of every LLM
                                decision, tool call, and final response from
                                the original run
    - trace.tool_calls      -> the denormalized mock tool inputs AND outputs

Replay does NOT call the LLM again. It walks the stored `events` in order
and, for every tool_call step, re-executes ONLY the mock tool handler (the
same ToolExecutionController used in Sections 5/8) with the exact recorded
tool_name/params against a freshly-seeded SandboxState — the same seed data
every scenario execution starts from (see SandboxState.fresh()). Because the
mock handlers in app/sandbox/tools.py are pure functions of (sandbox state
so far, params) with no randomness or wall-clock dependence, replaying the
same ordered sequence of calls against the same seed reproduces
byte-identical results. Comparing "replayed" vs. "originally recorded" tool
outputs is exactly the determinism guarantee this module exists to prove.

Non-tool-call steps (llm_decision, final_response, error) are carried
through unchanged from the stored trace — they are the deterministic
historical record, not something re-generated by the LLM.

This module never touches a real system: only the mock handlers in
app/sandbox/tools.py ever run, exactly as in the original execution.
"""
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Dict, List

from sqlalchemy.orm import Session, joinedload

from app.models.trace import Trace
from app.sandbox.registry import ToolExecutionController
from app.sandbox.state import SandboxState


class ReplayError(Exception):
    """Base class for replay-service errors."""


class TraceNotFoundError(ReplayError):
    pass


@dataclass
class ToolCallComparison:
    step: int
    tool_name: str
    params: Dict[str, Any]
    original_success: bool
    original_data: Dict[str, Any]
    original_error: str
    replayed_success: bool
    replayed_data: Dict[str, Any]
    replayed_error: str
    match: bool


@dataclass
class ReplayResult:
    trace: Trace
    timeline: List[Dict[str, Any]]
    comparisons: List[ToolCallComparison]
    deterministic: bool
    replayed_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))


def get_trace_for_replay(db: Session, trace_id: str) -> Trace:
    trace = (
        db.query(Trace)
        .options(
            joinedload(Trace.test_run),
            joinedload(Trace.failures),
        )
        .filter(Trace.id == trace_id)
        .first()
    )
    if trace is None:
        raise TraceNotFoundError(f"Trace '{trace_id}' not found")
    return trace


def replay_trace(db: Session, trace_id: str) -> ReplayResult:
    """The single entry point: load the stored trace, replay every recorded
    tool call against a fresh sandbox, and return the reconstructed timeline
    plus a deterministic/not-deterministic verdict."""
    trace = get_trace_for_replay(db, trace_id)

    controller = ToolExecutionController(SandboxState.fresh())
    comparisons: List[ToolCallComparison] = []
    timeline: List[Dict[str, Any]] = []
    deterministic = True

    for event in trace.events:
        step = event.get("step", 0)
        event_type = event.get("type")
        data = event.get("data") or {}

        if event_type != "tool_call":
            # llm_decision / final_response / error: replayed verbatim from
            # the stored record — the LLM is never called again.
            timeline.append({**event, "replay_matches_original": None})
            continue

        tool_name = data.get("tool_name", "")
        params = data.get("params") or {}
        original_success = bool(data.get("success", False))
        original_data = data.get("data") or {}
        original_error = data.get("error") or ""

        replayed = controller.execute(tool_name, params)
        replayed_error = replayed.error or ""

        match = (
            replayed.success == original_success
            and replayed.data == original_data
            and replayed_error == original_error
        )
        if not match:
            deterministic = False

        comparisons.append(
            ToolCallComparison(
                step=step,
                tool_name=tool_name,
                params=params,
                original_success=original_success,
                original_data=original_data,
                original_error=original_error,
                replayed_success=replayed.success,
                replayed_data=replayed.data,
                replayed_error=replayed_error,
                match=match,
            )
        )
        timeline.append({**event, "replay_matches_original": match})

    return ReplayResult(
        trace=trace,
        timeline=timeline,
        comparisons=comparisons,
        deterministic=deterministic,
    )
